@url = https://fantastic-couscous-4qjrr56x7x3j5-3000.app.github.dev/api/tarefas

GET {{url}}

###
POST {{url}}
Content-Type: application/json
    
{
    "id" : 10,
    "title" : "Executar Aplicação"
}

###
GET {{url}}/2